import AppHeader from "@/app/components/AppHeader/AppHeader";
import { AppMain } from "@/app/components/AppMain/AppMain.styles";
import GlobalStyle from "@/components/GlobalStyle.styles";
import { AuthProvider } from "@/context/AuthProvider";
import useCustomQueryClient from "@/hooks/useCustomQueryClient";
import {
  DehydratedState,
  Hydrate,
  QueryClientProvider,
} from "@tanstack/react-query";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import type { AppProps } from "next/app";
import Head from "next/head";

const App = ({
  Component,
  pageProps,
}: // https://github.com/vercel/next.js/issues/40372#issuecomment-1279963091
AppProps<{ dehydratedState: DehydratedState }>) => {
  const { customQueryClient: queryClient } = useCustomQueryClient();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <QueryClientProvider client={queryClient}>
        <Hydrate state={pageProps.dehydratedState}>
          <GlobalStyle />
          <AuthProvider>
            <AppHeader />
            <AppMain>
              <Component {...pageProps} />
            </AppMain>
          </AuthProvider>
        </Hydrate>
        <ReactQueryDevtools />
      </QueryClientProvider>
    </>
  );
};

export default App;
