import AppHeader from "@/components/AppHeader/AppHeader";
import { AppMain } from "@/components/AppMain/AppMain.styles";
import { Metadata } from "next";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1",
};

export default function RootLayout({
  // Layouts must accept a children prop.
  // This will be populated with nested layouts or pages
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <AppHeader />
          <AppMain>{children}</AppMain>
        </Providers>
      </body>
    </html>
  );
}
